"""Autonomy Boundary Skill for AI Agents and Chatbots.

Provides an importable, standardized skill interface that allows LLMs, chatbots,
and autonomous agent frameworks (LangChain, CrewAI, OpenAI Assistant, Anthropic tools)
to self-govern their actions through the Autonomy Boundary before executing effects.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Callable, Mapping

from abf.boundary import AutonomyBoundary
from abf.controls.legibility import approve, render_for_human
from abf.intent import Intent, canonicalize_target, snapshot_state
from abf.ledger import Ledger


@dataclass
class ProposedAction:
    """An action proposal generated by an agent chatbot."""

    intent: Intent
    requires_approval: bool
    approval_prompt: str
    status: str  # "ready_autonomous" | "requires_human_approval"

    def to_dict(self) -> dict[str, Any]:
        return {
            "intent_id": self.intent.intent_id,
            "intent_hash": self.intent.hash,
            "action": self.intent.action,
            "target": self.intent.effect_target,
            "params": dict(self.intent.params),
            "requires_approval": self.requires_approval,
            "approval_prompt": self.approval_prompt,
            "status": self.status,
        }


class AutonomyBoundarySkill:
    """Importable Skill adapter for AI Agents, Copilots, and Chatbots.

    Equips an agent with safe action proposal, consent legibility rendering,
    temporal state verification, and tamper-evident execution logging.
    """

    def __init__(
        self,
        boundary: AutonomyBoundary,
        signing_key: bytes,
        *,
        approver_key: bytes | None = None,
        agent_identity: str = "agent:chatbot",
        data_boundary: str = "*",
    ) -> None:
        self.boundary = boundary
        self.signing_key = signing_key
        self.approver_key = approver_key
        self.agent_identity = agent_identity
        self.data_boundary = data_boundary
        self._action_handlers: dict[str, Callable[[dict[str, Any]], Any]] = {}
        self._pending_intents: dict[str, Intent] = {}

    def register_action(
        self,
        action: str,
        handler: Callable[[dict[str, Any]], Any],
    ) -> None:
        """Registers the backend implementation for a governed action."""
        self._action_handlers[action] = handler

    def propose_action(
        self,
        action: str,
        resource: str,
        params: Mapping[str, Any] | None = None,
        *,
        capabilities: tuple[str, ...] | None = None,
        state_deps: Mapping[str, Any] | None = None,
        validity_window: str = "2099-01-01T00:00:00+00:00",
        expiry: str = "2099-01-01T00:00:00+00:00",
    ) -> ProposedAction:
        """Called by the agent before executing an action.

        Synthesizes a canonical intent, determines whether human approval
        is mandatory (via Reversibility), and generates the exact rendered prompt.
        """
        parameters = dict(params or {})
        resolved_target = canonicalize_target(resource)
        bound_state = snapshot_state(state_deps) if state_deps else {}

        intent = Intent(
            action=action,
            resource=resource,
            params=parameters,
            resolved_target=resolved_target,
            effective_identity=self.agent_identity,
            capabilities=capabilities or (action.split(".")[-1],),
            data_boundary=self.data_boundary,
            expiry=expiry,
            state_deps=bound_state,
            validity_window=validity_window if bound_state else "",
        ).sign(self.signing_key)

        # Cache pending proposal
        self._pending_intents[intent.hash] = intent

        # Check if reversibility requires human approval
        requires_approval = False
        for ctrl in self.boundary.controls:
            if ctrl.name == "reversibility":
                rev_result = ctrl.check(intent, {})
                if not rev_result.allowed:
                    requires_approval = True
                break

        status = "requires_human_approval" if requires_approval else "ready_autonomous"
        prompt = render_for_human(intent) if requires_approval else f"Autonomous action approved by policy: {intent.action}"

        return ProposedAction(
            intent=intent,
            requires_approval=requires_approval,
            approval_prompt=prompt,
            status=status,
        )

    def approve_proposal(
        self,
        intent_hash: str,
        approver: str,
        timestamp: str | None = None,
    ) -> dict[str, Any]:
        """Human approval action: creates a cryptographically signed approval token."""
        intent = self._pending_intents.get(intent_hash)
        if not intent:
            raise KeyError(f"no pending intent with hash {intent_hash}")

        return approve(
            intent,
            approver=approver,
            key=self.approver_key,
            timestamp=timestamp,
        )

    def execute_action(
        self,
        intent_hash: str,
        *,
        approval: dict[str, Any] | None = None,
        current_state: Mapping[str, Any] | None = None,
        task_spend: int = 0,
    ) -> Any:
        """Executes a previously proposed intent through the Autonomy Boundary."""
        intent = self._pending_intents.get(intent_hash)
        if not intent:
            raise KeyError(f"no pending intent with hash {intent_hash}")

        handler = self._action_handlers.get(intent.action)
        if not handler:
            raise PermissionError(f"no handler registered for action '{intent.action}'")

        context = {
            "approval": approval,
            "current_state": snapshot_state(current_state) if current_state else {},
            "task_spend": task_spend,
            "instance_id": self.agent_identity,
        }

        outcome = self.boundary.execute(intent, lambda i: handler(dict(i.params)), context)
        # Remove from pending once executed
        self._pending_intents.pop(intent_hash, None)
        return outcome

    def inspect_ledger(self) -> dict[str, Any]:
        """Inspects the decision ledger and asserts tamper-evidence."""
        is_intact = self.boundary.ledger.verify_chain()
        records = list(self.boundary.ledger.read())
        return {
            "chain_intact": is_intact,
            "record_count": len(records),
            "recent_records": records[-5:] if records else [],
        }

    def get_tool_declarations(self) -> list[dict[str, Any]]:
        """Returns standard OpenAI / Anthropic function calling tool definitions."""
        return [
            {
                "type": "function",
                "function": {
                    "name": "boundary_propose_action",
                    "description": "Propose an action to the Autonomy Boundary. Returns whether human approval is required.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "action": {"type": "string", "description": "Dotted verb, e.g. refund.issue, file.delete"},
                            "resource": {"type": "string", "description": "Target resource path or identifier"},
                            "params": {"type": "object", "description": "Parameters for the action"},
                        },
                        "required": ["action", "resource"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "boundary_execute_action",
                    "description": "Execute a permitted action with approval and live state validation.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "intent_hash": {"type": "string", "description": "Hash of the proposed intent"},
                        },
                        "required": ["intent_hash"],
                    },
                },
            },
            {
                "type": "function",
                "function": {
                    "name": "boundary_inspect_ledger",
                    "description": "Verify the mathematical tamper-evidence of the decision audit log.",
                    "parameters": {"type": "object", "properties": {}},
                },
            },
        ]
